In [1]:
import pandas as pd
import numpy as np
from sklearn import datasets
from sklearn.decomposition import PCA

/Users/serdar/anaconda3/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
/Users/serdar/anaconda3/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
/Users/serdar/anaconda3/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
/Users/serdar/anaconda3/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [2]:
iris = datasets.load_iris()
df = pd.DataFrame(iris.data, columns=iris.feature_names)

In [3]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

#### BEFORE PCA NORMALIZE THE DATA

In [4]:
df_norm = (df-df.mean())/df.std()

In [5]:
pca = PCA(n_components=4)
pca.fit_transform(df_norm.values)

array([[-2.25714118e+00,  4.78423832e-01, -1.27279624e-01,
        -2.40875085e-02],
       [-2.07401302e+00, -6.71882687e-01, -2.33825517e-01,
        -1.02662845e-01],
       [-2.35633511e+00, -3.40766425e-01,  4.40539002e-02,
        -2.82823051e-02],
       [-2.29170679e+00, -5.95399863e-01,  9.09852971e-02,
         6.57353401e-02],
       [-2.38186270e+00,  6.44675659e-01,  1.56856473e-02,
         3.58028703e-02],
       [-2.06870061e+00,  1.48420530e+00,  2.68782498e-02,
        -6.58611612e-03],
       [-2.43586845e+00,  4.74851181e-02,  3.34350297e-01,
         3.66527670e-02],
       [-2.22539189e+00,  2.22403002e-01, -8.83993519e-02,
         2.45299187e-02],
       [-2.32684533e+00, -1.11160370e+00,  1.44592465e-01,
         2.67695403e-02],
       [-2.17703491e+00, -4.67447569e-01, -2.52918268e-01,
         3.97660677e-02],
       [-2.15907699e+00,  1.04020587e+00, -2.67784001e-01,
        -1.66755027e-02],
       [-2.31836413e+00,  1.32633999e-01,  9.34461909e-02,
      

In [7]:
pca.explained_variance_ratio_
# we might say 3 component is enough to explain variation on y

array([0.72962445, 0.22850762, 0.03668922, 0.00517871])

In [14]:
df.shape

(150, 4)

In [10]:
np.identity(df.shape[1])

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [12]:
components = pca.transform(np.identity(df.shape[1]))
components

array([[ 0.52106591,  0.37741762, -0.71956635, -0.26128628],
       [-0.26934744,  0.92329566,  0.24438178,  0.12350962],
       [ 0.5804131 ,  0.02449161,  0.14212637,  0.80144925],
       [ 0.56485654,  0.06694199,  0.63427274, -0.52359713]])

In [16]:
pd.DataFrame(components, columns=['pc1', 'pc2', 'pc3', 'pc4'], index=df.columns)

pc1       pc2       pc3       pc4
sepal length (cm)  0.521066  0.377418 -0.719566 -0.261286
sepal width (cm)  -0.269347  0.923296  0.244382  0.123510
petal length (cm)  0.580413  0.024492  0.142126  0.801449
petal width (cm)   0.564857  0.066942  0.634273 -0.523597

In [17]:
## for pricipal component1, speal length (%51), petal length(58) and petal with (56%) explain the variation on y through pca

In [18]:
data = np.array([1,2,3])

In [19]:
data.prod()

6

In [21]:
data = np.array([[1,2], [3,4]])

In [23]:
data.prod()

24

In [24]:
data = np.array([[1,2],[3,4],[5,6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [25]:
data.max()

6

In [26]:
data.max(axis=0)

array([5, 6])