In [1]:
# dealing with non-linear data
# if one feature increaese the target increase or decrease there's a linear relationship but life is not much simple

In [4]:
from sklearn.preprocessing import PolynomialFeatures
import numpy as np

In [5]:
X = np.arange(4).reshape(2,2)

In [6]:
X

array([[0, 1],
       [2, 3]])

In [8]:
poly = PolynomialFeatures(degree=2)
poly.fit_transform(X)
# PolynomialFeatures converts our matrix into 2nd degree matrix

array([[1., 0., 1., 0., 0., 1.],
       [1., 2., 3., 4., 6., 9.]])

`[x1, x2] --> [1, x1, x2,  x1 ** 2,  x1 * x2,  x2 ** 2]`

In [9]:
from sklearn.linear_model import LinearRegression
from sklearn.pipeline import Pipeline

/Users/serdar/anaconda3/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [12]:
model = Pipeline([('poly', PolynomialFeatures(degree=3)),
                  ('linear', LinearRegression(fit_intercept=False))])

In [15]:
x = np.arange(5)
y = 3 - 2 * X + X ** 2 - x ** 3

In [17]:
np.stack([x,y])
# 1. sira x degerleri 2.row yukardaki formule gore karsilik gelen y degerleri

array([[  0,   1,   2,   3,   4],
       [  3,   1,  -5, -21, -53]])

In [20]:
model.fit(x[:, None], y)
# x[:, None] notice that I'm putting a call in common non hear. And, what this does is it creates 
# a new column index, so it transforms X from a list of numbers to an array of Lists, where each list is 
# a data point. So, it's an array of data points instead of just an array, and then we can fit this against y.           

Pipeline(memory=None,
     steps=[('poly', PolynomialFeatures(degree=3, include_bias=True, interaction_only=False)), ('linear', LinearRegression(copy_X=True, fit_intercept=False, n_jobs=None,
         normalize=False))])

In [22]:
model.named_steps['poly']

PolynomialFeatures(degree=3, include_bias=True, interaction_only=False)

In [23]:
model.named_steps['linear']

LinearRegression(copy_X=True, fit_intercept=False, n_jobs=None,
         normalize=False)

In [25]:
model.named_steps['linear'].coef_

# 3 is intercept, -2 is coef of x, 1 is coef of x^2 and -1 is coef of x^3 (we have 3rd degree poly)

array([ 3., -2.,  1., -1.])