In [1]:
import numpy as np
from sklearn.linear_model import LogisticRegression

In [4]:
feature_1 = np.random.randn(100)
feature_2 = 4 * np.random.randn(100)
feature_3 = 0.5 * np.random.randn(100)
class_labels = (3 + feature_1 + feature_2 + feature_3 + 0.5*np.random.randn())>= 0

In [6]:
X = np.column_stack([feature_1, feature_2, feature_3])

In [7]:
X

array([[-1.51241300e+00, -3.25060569e+00,  7.41919921e-01],
       [-1.78770520e-01, -1.23016671e+00,  3.68810838e-01],
       [ 7.46852374e-02, -6.24375559e+00,  2.16440801e-01],
       [-5.26149176e-01, -3.49508443e+00,  4.72989612e-02],
       [-2.36980572e-01,  5.10548600e-01, -9.54799175e-01],
       [ 1.05342238e+00, -4.22329937e+00,  3.35273084e-01],
       [-7.06037624e-02, -4.97907032e+00,  5.75452516e-01],
       [-1.89468706e+00,  2.73900292e+00, -1.27510154e+00],
       [-1.26027618e+00,  2.07783112e+00, -1.93603944e-02],
       [ 5.07768202e-01,  4.14379087e+00,  7.13995110e-02],
       [-9.40151924e-02, -2.33655029e+00,  1.01204192e+00],
       [-5.70870756e-01, -3.27403097e+00, -3.07359258e-01],
       [-1.32100185e+00, -6.83165939e+00,  6.60024044e-01],
       [ 9.78240192e-01,  4.74819831e+00,  3.62297378e-01],
       [-1.24357677e+00,  1.32732174e+00, -3.14228998e-01],
       [-5.96499489e-01,  1.37590288e+00,  4.63097611e-01],
       [-2.05667112e+00,  7.61380833e+00

In [10]:
np.random.randn(2)

array([0.35270332, 0.1937708 ])

In [11]:
class_labels

array([False,  True, False, False,  True,  True, False,  True,  True,
        True,  True, False, False,  True,  True,  True,  True, False,
        True,  True,  True,  True, False, False,  True,  True, False,
       False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True, False,
        True,  True, False,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
       False,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True])

In [12]:
model = LogisticRegression()

In [13]:
model.fit(X, class_labels)

/Users/serdar/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [14]:
model.coef_

array([[0.49323132, 1.05141564, 0.7443215 ]])

In [16]:
np.std(X,0) * model.coef_

array([[0.47025472, 3.83554574, 0.38160141]])