In [7]:
from sklearn import datasets
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np

In [16]:
X, y, answer = datasets.make_regression(n_samples=100, n_features=2, noise=10, coef=True )

In [17]:
X_train, X_test, y_train, y_test = train_test_split(X, y , test_size=0.5, random_state=42)

In [26]:
X_train[:10]

array([[ 0.80573312, -1.79381947],
       [ 0.11110144,  0.48780735],
       [ 1.88483935,  1.52159913],
       [ 0.04519088,  1.69117779],
       [-0.54181374,  0.93177119],
       [ 0.48255917, -1.72022735],
       [-0.46455219,  0.07215419],
       [-0.78242632,  0.91657355],
       [-0.21104791,  0.49877462],
       [ 2.41234534,  0.81306569]])

In [18]:
answer
## Those are the coef for 2 features (actula values) from the dummy data

array([64.76942649, 37.26275197])

In [19]:
model_lr = LinearRegression()

In [20]:
model_lr.fit(X_train, y_train)
model_lr.coef_
# Those are the coef prediction, which are close the actual coef values array([64.76942649, 37.26275197])

array([64.0008449 , 35.63544604])

### Another way to implement linear Regression

In [22]:
import statsmodels.formula.api as sm

In [29]:
df = pd.DataFrame(np.column_stack([X_train, y_train]))
df.columns=['f1', 'f2', 'y']

In [30]:
df.head()

f1        f2           y
0  0.805733 -1.793819   12.350718
1  0.111101  0.487807   11.336148
2  1.884839  1.521599  170.771103
3  0.045191  1.691178   44.083113
4 -0.541814  0.931771   14.537644

In [31]:
model_sm = sm.ols(formula ="y ~ f1 + f2", data=df).fit() 
## ols ordinary least squre

In [32]:
model_sm.params

Intercept     0.185979
f1           64.000845
f2           35.635446
dtype: float64

In [33]:
model_sm.summary()
# We get lots of information

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.981
Model:                            OLS   Adj. R-squared:                  0.980
Method:                 Least Squares   F-statistic:                     1183.
Date:                Mon, 24 Jun 2019   Prob (F-statistic):           6.40e-41
Time:                        23:14:09   Log-Likelihood:                -186.24
No. Observations:                  50   AIC:                             378.5
Df Residuals:                      47   BIC:                             384.2
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      0.1860      1.556      0.120      0.905      -2.944       3.316
f1            64.0008      1.526     41.942      0.000      60.931      67.071
f2            35.6354      1.642     21.705      0.000      32.333      38.938
==============================================================================
Omnibus:                        1.542   Durbin-Watson:                   1.955
Prob(Omnibus):                  0.463   Jarque-Bera (JB):                0.751
Skew:                          -0.076   Prob(JB):                        0.687
Kurtosis:                       3.581   Cond. No.                         1.43
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""